@UTB.Minute.WebApi_HostAddress = https://localhost:7254

GET {{UTB.Minute.WebApi_HostAddress}}/minuteMeals

###

POST {{UTB.Minute.WebApi_HostAddress}}/minuteMeals
Content-Type: application/json

{
  "desc": "Bolonske spagety",
  "price": 129.99
}

###

DELETE {{UTB.Minute.WebApi_HostAddress}}/minuteMeals/4

###
