@UTB.Minute.WebApi_HostAddress = https://localhost:7254

GET {{UTB.Minute.WebApi_HostAddress}}/minuteMeals

###

POST {{UTB.Minute.WebApi_HostAddress}}/minuteMeals
Content-Type: application/json

{
  "desc": "Bolonske spagety",
  "price": 129.99
}

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/minuteMeals/4/desc
Content-Type: application/json
{
  "desc": "Palacinky"
}

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/minuteMeals/4/price
Content-Type: application/json
{
  "price": 105.29
}

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/minuteMeals/4/active
Content-Type: application/json
{
  "isDeactivated": "true"
}

###