@UTB.Minute.WebApi_HostAddress = https://localhost:7254

GET {{UTB.Minute.WebApi_HostAddress}}/menuItems

###

POST {{UTB.Minute.WebApi_HostAddress}}/menuItems
Content-Type: application/json

{
  "date": "2026-05-20T10:11:30",
  "portions": 25,
  "minuteMealId": 2
}

###

DELETE {{UTB.Minute.WebApi_HostAddress}}/menuItems/1

###

PUT {{UTB.Minute.WebApi_HostAddress}}/menuItems/2
Content-Type: application/json

{
  "date": "2026-03-10T10:25:00",
  "portions": 11,
  "minuteMealId": 2
}

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/menuItems/1/date
Content-Type: application/json

{
  "date": "2026-04-18T11:38:00"
}

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/menuItems/1/meal
Content-Type: application/json

{
  "minuteMealId": 2
}

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/menuItems/2/portion

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/menuItems/1/portions
Content-Type: application/json

{
  "portions" : 12
}

###

GET {{UTB.Minute.WebApi_HostAddress}}/minuteMeals

###

GET {{UTB.Minute.WebApi_HostAddress}}/minuteMeals/active

###

POST {{UTB.Minute.WebApi_HostAddress}}/minuteMeals
Content-Type: application/json

{
  "desc": "Bolonske spagety",
  "price": 129.99,
  "isActive": false
}

###

PUT {{UTB.Minute.WebApi_HostAddress}}/minuteMeals/2
Content-Type: application/json

{
  "desc": "test",
  "price": 125.89,
  "isActive": false
}
###

PATCH {{UTB.Minute.WebApi_HostAddress}}/minuteMeals/4/active
Content-Type: application/json

{
  "isActive": false
}

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/minuteMeals/4/desc
Content-Type: application/json

{
  "desc": "Palacinky"
}

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/minuteMeals/4/price
Content-Type: application/json

{
  "price": 105.29
}

###

GET {{UTB.Minute.WebApi_HostAddress}}/orders

###

POST {{UTB.Minute.WebApi_HostAddress}}/orders
Content-Type: application/json

{
  "status": 1,
  "menuItemId": 3
}

###

PUT {{UTB.Minute.WebApi_HostAddress}}/orders/1
Content-Type: application/json

{
  "status": 2,
  "menuItemId": 3
}

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/orders/1/menuItem
Content-Type: application/json

{
  "menuItemId": 2
}

###

PATCH {{UTB.Minute.WebApi_HostAddress}}/orders/1/status
Content-Type: application/json

{
  "status": 3
}

###
